add version command add version check to docker build

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -15,6 +15,7 @@ RUN echo "permit nopass keepenv xbot" >/etc/doas.conf
 
 RUN mkdir /home/xbot/.vnc
 COPY xstartup /home/xbot/.vnc/xstartup
+
 RUN echo vncvnc | vncpasswd -f >/home/xbot/.vnc/passwd && \
     chmod 700 /home/xbot/.vnc/xstartup && \
     chmod 600 /home/xbot/.vnc/passwd && \
@@ -29,10 +30,12 @@ USER xbot
 WORKDIR /home/xbot
 RUN echo "export PATH=$HOME/.local/bin:$PATH" >>.bashrc
 
-RUN \
-    export PATH=${HOME}/.local/bin:${PATH} && \
-    pipx install baikalctl && \
-    baikalctl --version
+RUN export PATH=${HOME}/.local/bin:${PATH}; pipx install baikalctl
+
+COPY --chmod=0444 VERSION VERSION
+RUN echo VERSION=$(cat VERSION) 
+RUN ./local/bin/baikalctl version
+RUN if [ "$(cat VERSION)" != "$(.local/bin/baikalctl version)" ]; then { echo "Version mismatch failure."; exit 1; }; fi
 
 ENV DISPLAY=:1
 
